### ISSUE TITLE
named-parameters and settingslogic can not be used together

### ISSUE THREAD

**Issue by tomeric** [jurisgalang/named-parameters#3]
Hi,

I've got a project that tries to use fog (which depends on this gem) and settingslogic together, but this results in an exception whenever the two are required after each other.

Here is a backtrace of an IRB session:

```
ruby-1.9.2-p0 > require 'named-parameters'
 => true 
ruby-1.9.2-p0 > require 'settingslogic'
NameError: undefined local variable or method `instance' for Settingslogic:Class
    from /Users/tomeric/.rvm/gems/ruby-1.9.2-p0@busboy/gems/settingslogic-2.0.6/lib/settingslogic.rb:10:in `name'
```

**Comment by jurisgalang** [comment]
Does `require "settinglogic"` also implies it that it `requires "fog"`? I don't think it's necessary to `require "named-parameters"` if that's the case (as "fog" would've loaded "named-parameters" already)

Is `settinglogic` available here on github? I could take a look...

**Comment by jurisgalang** [comment]
I've got the following installed:

```
fog (0.3.30)
named-parameters (0.0.17)
settingslogic (2.0.6)
```

This works:

```
$ irb
ruby-1.9.2-p0 > require 'settingslogic'
=> true 
ruby-1.9.2-p0 > require 'fog'
=> true 
```

This however will fail, like you illustrated:

```
$ irb
ruby-1.9.2-p0 > require 'fog'
=> true 
ruby-1.9.2-p0 > require 'settingslogic'
NameError: undefined local variable or method `instance' for Settingslogic:Class
    from /Users/jgalang/.rvm/gems/ruby-1.9.2-p0/gems/settingslogic-
2.0.6/lib/settingslogic.rb:10:in `name'
    from /Users/jgalang/.rvm/gems/ruby-1.9.2-p0/gems/named-parameters-
0.0.17/lib/named-parameters/module.rb:367:in `key_for'
...
```

I looked at the source of `settingslogic`, it does not require `fog` right away so the above sequence of require might a work-around that you could use for now.

I'll investigate the issue later today.

**Comment by tomeric** [comment]
Yes, I found that out too, but unfortunately bundler does not allow me to change the order in which I require files. Forcing settingslogic to load earlier manually led to StackError's. 

I'm now using an older version of fog that is not dependent on this library.

**Comment by jurisgalang** [comment]
That sucks a bit (re: bundler and load orders) - looks like it was [discussed](http://yehudakatz.com/2010/04/17/ruby-require-order-problems/) back in April...

Anyway, I'll investigate your issue today.

**Comment by jurisgalang** [comment]
Here's a fix, so you can use the latest and greatest `fog`. Looks good, but I'd like to test it a bit more on my side:

```
diff --git a/lib/named-parameters/module.rb b/lib/named-parameters/module.rb
index 217aeed..2df6f8e 100644
--- a/lib/named-parameters/module.rb
+++ b/lib/named-parameters/module.rb
@@ -299,7 +299,7 @@ module NamedParameters
       apply_method_spec :"self.#{name}" do
         method = self.eigenclass.instance_method name
         spec   = method_specs[key_for :"self.#{name}"]
-        owner  = "#{self.name}::"
+        owner  = "#{self}::"
         eigenclass.instance_eval do
           intercept method, owner, name, spec
         end
@@ -312,7 +312,7 @@ module NamedParameters
       apply_method_spec name do
         method = instance_method name
         spec   = method_specs[key_for name]
-        owner  = "#{self.name}#"
+        owner  = "#{self}#"
         intercept method, owner, name, spec
       end
       super
@@ -364,7 +364,7 @@ module NamedParameters
     def key_for method
       type = method.to_s =~ /^self\./ ? :singleton : :instance
       name = method.to_s.sub(/^self\./, '')
-      :"#{self.name}::#{type}.#{name}"
+      :"#{self}::#{type}.#{name}"
     end

     # check if in the process of instrumenting a method
```

**Comment by jurisgalang** [comment]
I pushed release `0.0.18` for `named-parameters`. This should fix the issue you encountered. If you find anything else, tell me - otherwise I'll consider this issue closed by tomorrow.

**Comment by jurisgalang** [comment]
Closing. `0.0.18` fixed this.
