### ISSUE TITLE
1.8.6 bug, shows itself from fog binary

### ISSUE THREAD

**Issue by geemus** [jurisgalang/named-parameters#4]
when I try to run the fog binary I get some warnings and an error if I'm running 1.8.6
    /Library/Ruby/Gems/1.8/gems/named-parameters-0.0.18/lib/named-parameters/module.rb:241: warning: parenthesize argument(s) for future version
    /Library/Ruby/Gems/1.8/gems/named-parameters-0.0.18/lib/named-parameters/module.rb:258: warning: parenthesize argument(s) for future version
    /Library/Ruby/Gems/1.8/gems/named-parameters-0.0.18/lib/named-parameters/module.rb:301: warning: parenthesize argument(s) for future version
    /Library/Ruby/Gems/1.8/gems/named-parameters-0.0.18/lib/named-parameters/module.rb:314: warning: parenthesize argument(s) for future version
    /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /Library/Ruby/Gems/1.8/gems/named-parameters-0.0.18/lib/named-parameters/module.rb:334: syntax error, unexpected ',', expecting '|' (SyntaxError)
          define_method name do |*args, &block|
                                       ^
    /Library/Ruby/Gems/1.8/gems/named-parameters-0.0.18/lib/named-parameters/module.rb:380: syntax error, unexpected kEND, expecting $end
      from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in`require'
      from /Library/Ruby/Gems/1.8/gems/named-parameters-0.0.18/lib/named-parameters.rb:4
      from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
      from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in`require'
      from /Library/Ruby/Gems/1.8/gems/fog-0.3.30/lib/fog.rb:7
      from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
      from /Library/Ruby/Site/1.8/rubygems/custom_require.rb:31:in`require'
      from /Library/Ruby/Gems/1.8/gems/fog-0.3.30/bin/fog:2
      from /usr/bin/fog:19:in `load'
      from /usr/bin/fog:19

**Comment by jurisgalang** [comment]
Hmmm. Will check this out tonight...

**Comment by jurisgalang** [comment]
The latest release makes it compatible with `Ruby 1.8.6`
Here's `fog` using the latest under `1.8.6`:

```
(jgalang@hanzo:fog)
$ pwd 
/Users/jgalang/Code/opensource/fog

(jgalang@hanzo:fog)
$ rvm use 1.8.6
Using /Users/jgalang/.rvm/gems/ruby-1.8.6-p399

(jgalang@hanzo:fog)
$ ./bin/fog 
  Welcome to fog interactive!
  :default credentials provide AWS, Bluebox, Brightbox, GoGrid, Google, Linode, Local, NewServers, Rackspace and Slicehost
  You have access to the following Vcloud services: :ecloud, :vcloud.
>> Fog::Google::Storage.new
#<Fog::Google::Storage::Real:0x101a0f918 @connection=#<Fog::Connection:0x101bd5f18 @persistent=true, @excon=#<Excon::Connection:0x101bd5e78 @connection={:scheme=>"https", :socket_key=>"commondatastorage.googleapis.com:443", :path=>"", :headers=>{}, :query=>nil, :port=>443, :host=>"commondatastorage.googleapis.com"}>>, @google_storage_access_key_id="INTENTIONALLY_LEFT_BLANK", @port=443, @scheme="https", @host="commondatastorage.googleapis.com", @google_storage_secret_access_key="INTENTIONALLY_LEFT_BLANK", @hmac=#<Fog::HMAC:0x101bd6120 @signer=#<Proc:0x00000001010ef0b8@/Users/jgalang/Code/opensource/fog/lib/fog/core/hmac.rb:22>, @digest=da39a3ee5e6b4b0d3255bfef95601890afd80709, @key="INTENTIONALLY_LEFT_BLANK">>
>>
```
